context:
  name: mike
  version: "2.1.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/mike-${{ version }}.tar.gz
  sha256: 75d549420b134603805a65fc67f7dcd9fcd0ad1454fb2c893d9e844cba1aa6e4

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - mike = mike.driver:main

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    - jinja2 >=2.7
    - mkdocs >=1.0
    - pyparsing >=3.0
    - pyaml >=5.1
    - verspec
    - pyyaml-env-tag
    - importlib-resources
    - importlib-metadata

tests:
  - python:
      imports:
        - mike
        - mike.templates
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - mike --help

about:
  summary: Manage multiple versions of your MkDocs-powered documentation
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/jimporter/mike

extra:
  recipe-maintainers:
    - hadim
